import type { CalendarTask, CalendarUser } from "@/lib/types";

export const demoUsers: CalendarUser[] = [
  {
    id: "u-admin",
    name: "田中太郎",
    email: "admin@ag.example",
    role: "admin",
    color: "#2f6fed",
  },
  {
    id: "u-zhang",
    name: "张三",
    email: "zhangsan@ag.example",
    role: "member",
    color: "#17a765",
  },
  {
    id: "u-li",
    name: "李四",
    email: "lisi@ag.example",
    role: "member",
    color: "#f5a623",
  },
  {
    id: "u-wang",
    name: "王五",
    email: "wangwu@ag.example",
    role: "member",
    color: "#e5534b",
  },
  {
    id: "u-zhao",
    name: "赵六",
    email: "zhaoliu@ag.example",
    role: "member",
    color: "#00a2ae",
  },
  {
    id: "u-qian",
    name: "钱七",
    email: "qianqi@ag.example",
    role: "member",
    color: "#7f56d9",
  },
  {
    id: "u-sun",
    name: "孙八",
    email: "sunba@ag.example",
    role: "member",
    color: "#d9480f",
  },
  {
    id: "u-zhou",
    name: "周九",
    email: "zhoujiu@ag.example",
    role: "member",
    color: "#0f766e",
  },
  {
    id: "u-wu",
    name: "吴十",
    email: "wushi@ag.example",
    role: "member",
    color: "#be185d",
  },
  {
    id: "u-zheng",
    name: "郑十一",
    email: "zhengshiyi@ag.example",
    role: "member",
    color: "#2563eb",
  },
];

export const demoTasks: CalendarTask[] = [
  {
    id: "t-1",
    title: "办公室电脑安装",
    description: "三层办公室新增工位，完成电脑安装、网络连通和账号登录检查。",
    startsAt: "2026-07-02T10:00:00+08:00",
    status: "doing",
    priority: "high",
    createdBy: "u-admin",
    assigneeIds: ["u-zhang", "u-li"],
  },
  {
    id: "t-2",
    title: "招生资料更新",
    description: "更新招生说明 PDF，补充 2026 年课程排期。",
    startsAt: "2026-07-03T14:00:00+08:00",
    status: "todo",
    priority: "normal",
    createdBy: "u-admin",
    assigneeIds: ["u-li"],
  },
  {
    id: "t-3",
    title: "校内网络巡检",
    description: "检查会议室和前台无线网络，记录异常 AP。",
    startsAt: "2026-07-06T09:30:00+08:00",
    status: "done",
    priority: "normal",
    createdBy: "u-zhang",
    assigneeIds: ["u-zhang"],
  },
  {
    id: "t-4",
    title: "工资发放确认",
    description: "确认本月员工工资发放数据，处理遗漏项。",
    startsAt: "2026-07-10T11:00:00+08:00",
    status: "todo",
    priority: "high",
    createdBy: "u-admin",
    assigneeIds: ["u-admin"],
  },
  {
    id: "t-5",
    title: "教材采购",
    description: "统计缺货教材并提交采购清单。",
    startsAt: "2026-07-14T15:00:00+08:00",
    status: "doing",
    priority: "normal",
    createdBy: "u-admin",
    assigneeIds: ["u-wang"],
  },
  {
    id: "t-6",
    title: "员工面谈",
    description: "新员工试用期沟通，记录后续培养计划。",
    startsAt: "2026-07-17T16:00:00+08:00",
    status: "todo",
    priority: "low",
    createdBy: "u-admin",
    assigneeIds: ["u-zhang", "u-wang"],
  },
  {
    id: "t-7",
    title: "系统备份检查",
    description: "检查 Supabase 备份策略和本地导出脚本。",
    startsAt: "2026-07-21T10:30:00+08:00",
    status: "todo",
    priority: "normal",
    createdBy: "u-li",
    assigneeIds: ["u-li"],
  },
  {
    id: "t-8",
    title: "紧急设备故障",
    description: "前台打印机无法连接，确认驱动和局域网状态。",
    startsAt: "2026-07-24T13:30:00+08:00",
    status: "doing",
    priority: "high",
    createdBy: "u-wang",
    assigneeIds: ["u-wang", "u-zhang"],
  },
];
